project_id = "wnkxrqyovffosuppzujn"

[functions.gsheets-api]
verify_jwt = false

[functions.gsheets-init]
verify_jwt = false

[functions.upload-to-gdrive]
verify_jwt = false

[functions.stt]
verify_jwt = false

[functions.ai-task-parser]
verify_jwt = false

[functions.task-reminder-cron]
verify_jwt = false

[functions.feedback]
verify_jwt = false
